// This file has to be in JavaScript, otherwise @docusaurus/plugin-content-docs doesn't work properly
export default {
    quill: [
        {
            type: "category",
            label: "Quill",
            link: {
                type: "doc",
                id: "home",
            },
            collapsible: false,
            items: [{ type: "autogenerated", dirName: "." }],
        },
    ],
};
