// This file has to be in JavaScript, otherwise @docusaurus/plugin-content-docs doesn't work properly
export default {
    cloud: [
        {
            type: 'category',
            label: 'Cloud',
            link: {
                type: 'doc',
                id: 'home',
            },
            items: [
                {
                    type: 'doc',
                    id: 'home',
                    label: 'Home',
                    className: 'hidden' // <-- This makes the default item invisible, while still rendering the sidebar
                },
                {
                    type: 'doc',
                    id: 'cloud-overview',
                    label: 'Overview'
                },
                {
                    type: 'category',
                    label: 'Portal',
                    items: [{ type: 'autogenerated', dirName: 'portal' }],
                },
                {
                    type: 'doc',
                    id: 'cloud-instances',
                    label: 'Tiers and Instances'
                },
                {
                    type: 'doc',
                    id: 'cloud-pricing-payment-billing',
                    label: 'Pricing, Payment and Billing',
                },
                {
                    type: 'doc',
                    id: 'cloud-backup-and-restore',
                    label: 'Backup And Restore',
                },
                {
                    type: 'doc',
                    id: 'cloud-migration',
                    label: 'Migration',
                },
                {
                    type: 'doc',
                    id: 'cloud-scaling',
                    label: 'Scaling'
                },
                {
                    type: 'doc',
                    id: 'cloud-security',
                    label: 'Security'
                },
                {
                    type: 'doc',
                    id: 'cloud-api',
                    label: 'API'
                },
                {
                    type: 'doc',
                    id: 'cloud-settings',
                    label: 'Settings'
                },
                {
                    type: 'doc',
                    id: 'cloud-support',
                    label: 'Support'
                },
                {
                    type: 'doc',
                    id: 'cloud-account',
                    label: 'Account'
                },
                {
                    type: 'doc',
                    id: 'cloud-maintenance-troubleshooting',
                    label: 'Maintenance & Troubleshooting'
                },
                {
                    type: 'doc',
                    id: 'cloud-features',
                    label: 'Product Features',
                },
                {
                    type: 'doc',
                    id: 'cloud-microsoft-azure-marketplace',
                    label: 'Microsoft Azure Marketplace',
                },
                {
                    type: 'doc',
                    id: 'cloud-aws-marketplace',
                    label: 'AWS Marketplace',
                },
            ]
        }
    ],
};
