import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    docs: [
        {
            type: 'category',
            label: 'Docs',
            link: {
                type: 'doc',
                id: 'home',
            },
            items: [
                {
                    type: 'doc',
                    id: 'whats-new',
                    label: 'Whats New',
                    className: 'hidden'
                },
                {
                    type: 'category',
                    label: 'Getting Started',
                    items: [{type: 'autogenerated', dirName: 'start'}],
                },
                {
                    type: 'category',
                    label: 'Client API',
                    items: [{type: 'autogenerated', dirName: 'client-api'}],
                },
                {
                    type: 'category',
                    label: 'Indexes',
                    items: [{type: 'autogenerated', dirName: 'indexes'}],
                },
                {
                    type: 'category',
                    label: 'Documents',
                    items: [{type: 'autogenerated', dirName: 'documents'}],
                },
                {
                    type: 'category',
                    label: 'Document Extensions',
                    items: [{type: 'autogenerated', dirName: 'document-extensions'}],
                },
                {
                    type: 'category',
                    label: 'Data Archival',
                    items: [{type: 'autogenerated', dirName: 'data-archival'}],
                },
                {
                    type: 'category',
                    label: 'Compare-Exchange',
                    items: [{type: 'autogenerated', dirName: 'compare-exchange'}],
                },
                {
                    type: 'category',
                    label: 'Server',
                    items: [{type: 'autogenerated', dirName: 'server'}],
                },
                {
                    type: 'category',
                    label: 'Studio',
                    items: [{type: 'autogenerated', dirName: 'studio'}],
                },
                {
                    type: 'category',
                    label: 'Migration Guide',
                    items: [{type: 'autogenerated', dirName: 'migration'}],
                },
                {
                    type: 'category',
                    label: 'Integrations',
                    items: [{type: 'autogenerated', dirName: 'integrations'}],
                },
                {
                    type: 'category',
                    label: 'AI Integration',
                    items: [{type: 'autogenerated', dirName: 'ai-integration'}],
                },
                {
                    type: 'category',
                    label: 'Glossary',
                    items: [{type: 'autogenerated', dirName: 'glossary'}],
                },
                {
                    type: 'category',
                    label: 'Users Issues',
                    items: [{type: 'autogenerated', dirName: 'users-issues'}],
                },
                {
                    type: 'category',
                    label: 'Sharding',
                    items: [{type: 'autogenerated', dirName: 'sharding'}],
                }
            ]
        }
    ]
};

export default sidebars;
