namespace Raven.Documentation.Samples.ClientApi.DocumentIdentifiers
{
	using Client.Document;
	using CodeSamples.Orders;
	using Json.Linq;

	public class WorkingWithDocumentIds
	{
		public WorkingWithDocumentIds()
		{
			var store = new DocumentStore();

			var session = store.OpenSession();

			#region session_id_not_provided

			var order = new Order()
			{
				Id = null // value not provided
			};

			session.Store(order);

			#endregion


			#region session_get_document_id

			var orderId = session.Advanced.GetDocumentId(order); // "orders/1"

			#endregion

			#region session_empty_string_id

			var orderEmptyId = new Order()
			{
				Id = string.Empty // database will create a GUID value for it
			};

			session.Store(orderEmptyId);

			session.SaveChanges();

			var guidId = session.Advanced.GetDocumentId(orderEmptyId); // "6778c231-180b-4715-aad4-253c4c6027a4"

			#endregion

			#region session_semantic_id_1
			var product = new Product()
			{
				Id = "products/ravendb",
				Name = "RavenDB"
			};

			session.Store(product);
			#endregion

			#region session_semantic_id_2
			session.Store(new Product() { Name = "RavenDB" }, "products/ravendb");
			#endregion


			#region session_identity_id
			session.Store(new Company()
			{
				Id = "companies/"
			});

			session.Store(new Company()
			{
				Id = "companies/"
			});

			session.SaveChanges();
			#endregion

			#region commands_autogenerated_guid
			var result = store.DatabaseCommands.Put(null, null, new RavenJObject(){ {"Name", "RavenDB"}}, new RavenJObject());

			var key = result.Key;
			#endregion
		} 
	}
}